num_righe(10).
num_colonne(10).
iniziale(pos(1,2)).
finale(pos(8,3)).
finale(pos(9,9)).
occupata(pos(3,2)).
occupata(pos(3,6)).
occupata(pos(3,7)).
occupata(pos(3,8)).
occupata(pos(3,9)).
occupata(pos(4,2)).
occupata(pos(4,3)).
occupata(pos(4,6)).
occupata(pos(4,7)).
occupata(pos(4,8)).
occupata(pos(4,9)).
occupata(pos(5,2)).
occupata(pos(5,3)).
occupata(pos(5,4)).
occupata(pos(5,7)).
occupata(pos(5,8)).
occupata(pos(5,9)).
occupata(pos(6,2)).
occupata(pos(6,3)).
occupata(pos(6,4)).
occupata(pos(6,5)).
occupata(pos(6,8)).
occupata(pos(6,9)).
occupata(pos(7,2)).
occupata(pos(7,3)).
occupata(pos(7,4)).
occupata(pos(7,5)).
occupata(pos(7,9)).
occupata(pos(8,2)).
occupata(pos(9,2)).
occupata(pos(9,3)).
occupata(pos(9,4)).
occupata(pos(9,5)).
occupata(pos(9,6)).