num_righe(5).
num_colonne(5).
iniziale(pos(3,3)).
finale(pos(1,5)).
finale(pos(5,1)).
occupata(pos(1,1)).
occupata(pos(1,2)).
occupata(pos(1,3)).
occupata(pos(2,1)).
occupata(pos(3,1)).
occupata(pos(3,5)).
occupata(pos(4,5)).
occupata(pos(5,3)).
occupata(pos(5,4)).
occupata(pos(5,5)).
